---
title: "Assignment 4"
author: "Me"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}

options(scipen=10000000)
library(tidyverse)
library(kableExtra)
library(caret)
library(knitr) 
library(pscl)
library(plotROC)
library(pROC)
library(lubridate)
library(gridExtra)

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#981FAC","#CB0F8B","#FF006A","#FE4C35","#FE9900")
palette4 <- c("#981FAC","#FF006A","#FE4C35","#FE9900")
palette2 <- c("#981FAC","#FF006A")


housing <- read.csv("~/GitHub/MUSA-508/housingSubsidy.csv")

housing <-
  housing %>%
  na.omit()
```

```{r cars}
#Data Visualization
housing %>%
  dplyr::select(y,unemploy_rate, spent_on_repairs, age, campaign, 
                previous,cons.price.idx,cons.conf.idx) %>%
  gather(Variable, value, -y) %>%
    ggplot(aes(y, value, fill=y)) + 
      geom_bar(position = "dodge", stat = "summary", fun.y = "mean") + 
      facet_wrap(~Variable, scales = "free") +
      scale_fill_manual(values = palette2) +
      labs(x="Used Credit", y="Value", 
           title = "Figure 1: Feature associations with the likelihood of taking tax credit",
           subtitle = "(continous outcomes)") +
      theme(legend.position = "none")
      
# Continuous (Yes/No)
housing %>%
  dplyr::select(y,mortgage, taxbill_in_phl, taxLien) %>%
  gather(Variable, value, -y) %>%
  count(Variable, value, y) %>%
    ggplot(aes(y, n, fill=y)) + 
      geom_bar(position = "dodge", stat = "summary", fun.y = "mean") + 
      facet_wrap(~Variable, scales = "free") +
      scale_fill_manual(values = palette2) +
      labs(x="Used Credit", y="Value", 
           title = "Figure 2: Feature associations with the likelihood of taking tax credit",
           subtitle = "(Yes/No)") +
      theme(legend.position = "none")
      
# Categorical
housing %>% #make font smaller OR 
  dplyr::select(y, job, marital, education, contact, month, day_of_week) %>%
  gather(Variable, value, -y) %>%
  count(Variable, value, y) %>%
  ggplot(aes(value, n, fill = y)) +   
    geom_bar(position = "dodge", stat="identity") +
    facet_wrap(~Variable, scales="free") +
    scale_fill_manual(values = palette2) +
    labs(x="Took Credit", y="Count",
         title = "Figure 3: Feature associations with the likelihood of taking tax credit",
         subtitle = "Multiple category features") +
    theme(axis.text.x = element_text(angle=45, hjust=1))
```

#Feature Engineering
```{r cars}
# Season
housing <-
  housing %>%
  mutate(Season = case_when(
    month == "dec" |month == "jan" | month == "feb" ~ "Winter",
    month == "mar" |month == "apr" | month == "may" ~ "Spring",
    month == "jun" |month == "jul" | month == "aug" ~ "Summer",
    month == "sep" |month == "oct" | month == "nov" ~ "Fall"))

# Education
housing <-
  housing %>%
  mutate(Education = case_when(
    education == "basic.9y" |education == "basic.6y" | education == "basic.4y" ~ "Less Than HS",
    education == "high.school"  ~ "High School",
    education == "university.degree" |education == "professional.course"  ~ "Higher Education",
    education == "unknown" |education == "illiterate"  ~ "Illiterate"))

# Previous Program Contact
housing <-
  housing %>%
  mutate(Contact = case_when(pdays == 999 ~ "No Contact",
                                 pdays < 7 ~ "One week",
                                 pdays >= 7 & pdays < 21 ~ "2 Weeks",
                             pdays >= 22 & pdays < 29 ~ "3 Weeks",
                               pdays >= 30 ~ "More than 3 Weeks"))
# Employment Stauts
housing <- 
  housing %>% 
  mutate(EmploymentStatus = case_when(job == "student" | job == "unemployed" | job == "retired" ~ "unemployed",
                                   TRUE  ~ "employed"))
# Age Groups         
housing <-
  housing %>%
  mutate(Age = case_when(
    age >= 18 & age < 22  ~ "Gen Z",
    age >= 23 & age < 38  ~ "Millenials",
    age >= 39 & age < 54  ~ "Gen X",
    TRUE ~ "Boomer"))
```


```{r , echo=FALSE}
set.seed(3456)
subsidyIndex <- createDataPartition(y = paste(housing$taxLien),  p = .65, list = FALSE, times = 1)
subsidyTrain <- housing[ subsidyIndex,]
subsidyTest  <- housing[-subsidyIndex,]
```


```{r , echo=FALSE}
# Kitchen Sink
housingreg_kitchensink <- glm(y_numeric ~ .,
                  data=subsidyTrain %>% dplyr::select(-Age, -Education, -Season, -Contact, -EmploymentStatus, -X, -y),
                  family="binomial" (link="logit"))
summary(housingreg_kitchensink)

pR2(housingreg_kitchensink) 
```


```{r , echo=FALSE}
housingreg_engine <- glm(y_numeric ~ .,
                  data=subsidyTrain %>% dplyr::select(-age, -month, -education, 
                                                      -pdays, -job, -X, -y), #unsure about -X and -y
                  family="binomial" (link="logit")) 
                  
summary(housingreg_engine)

pR2(housingreg_engine)
```


```{r , echo=FALSE}
testProbs <- data.frame(Outcome = as.factor(subsidyTest$y_numeric),
                        Probs = predict(housingreg_engine, subsidyTest, type= "response"))

head(testProbs)

testProbs <-
  testProbs %>%
  na.omit()

ggplot(testProbs, aes(x = Probs, fill = as.factor(Outcome))) + 
  geom_density() +
  facet_grid(Outcome ~ .) +
  scale_fill_manual(values = palette2) +
  labs(x = "Credit", y = "Density of probabilities",
       title = "Figure 4: Distribution of predicted probabilities by observed outcome") +
  theme(strip.text.x = element_text(size = 18),
        legend.position = "none")
```

#Confusion Matrix
```{r , echo=FALSE}
testProbs <- 
  testProbs %>%
  mutate(predOutcome  = as.factor(ifelse(testProbs$Probs > 0.5 , 1, 0)))

caret::confusionMatrix(testProbs$predOutcome, testProbs$Outcome, 
                       positive = "1")
```

#ROC Curve
```{r , echo=FALSE}
ggplot(testProbs, aes(d = as.numeric(testProbs$Outcome), m = Probs)) +
  geom_roc(n.cuts = 50, labels = FALSE, colour = "#FE9900") +
  style_roc(theme = theme_grey) +
  geom_abline(slope = 1, intercept = 0, size = 1.5, color = 'grey') +
  labs(title = "Figure 5: ROC Curve - Tax Credit")

pROC::auc(testProbs$Outcome, testProbs$Probs)
```

#Cross Validation
```{r , echo=FALSE}
ctrl <- trainControl(method = "cv", number = 100, classProbs=TRUE, summaryFunction=twoClassSummary)


cvFit_engine <- train(y ~ .,
                  data = housing %>% 
                    na.omit() %>%
                    dplyr::select(-age, -month, -education, -pdays, -job, -X, -y_numeric),
                method="glm", family="binomial",
                metric="ROC", trControl = ctrl) 

cvFit_kitchensink <- train(y ~ .,
                  data = housing %>% 
                    dplyr::select(-Age, -Education, -Season, -Contact, -EmploymentStatus, -X, -y_numeric), 
                method="glm", family="binomial",
                metric="ROC", trControl = ctrl)

grid.arrange(ncol = 1, 

  dplyr::select(cvFit_kitchensink$resample, -Resample) %>%
  gather(metric, value) %>%
  left_join(gather(cvFit_kitchensink$results[2:4], metric, mean)) %>%
  ggplot(aes(value)) + 
  geom_histogram(bins=35, fill = "#FF006A") +
  facet_wrap(~metric) +
  geom_vline(aes(xintercept = mean), colour = "#981FAC", linetype = 3, size = 1.5) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x="Goodness of Fit", y="Count", title="Figure 6: CV Goodness of Fit Metrics \n Kitchen Sink Model",
       subtitle = "Across-fold mean reprented as dotted lines"),


  dplyr::select(cvFit_engine$resample, -Resample) %>%
  gather(metric, value) %>%
  left_join(gather(cvFit_engine$results[2:4], metric, mean)) %>%
  ggplot(aes(value)) + 
  geom_histogram(bins=35, fill = "#FF006A") +
  facet_wrap(~metric) +
  geom_vline(aes(xintercept = mean), colour = "#981FAC", linetype = 3, size = 1.5) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x="Goodness of Fit", y="Count", title="Figure 7 CV Goodness of Fit Metrics \n Feature Engineered Model",
       subtitle = "Across-fold mean reprented as dotted lines"))
```

#Cost Benefit Analysis
```{r , echo=FALSE}
cost_benefit_table <- # Check math
   testProbs %>%
      count(predOutcome, Outcome) %>%
      summarize(True_Negative = sum(n[predOutcome==0 & Outcome==0]),
                True_Positive = sum(n[predOutcome==1 & Outcome==1]),
                False_Negative = sum(n[predOutcome==0 & Outcome==1]),
                False_Positive = sum(n[predOutcome==1 & Outcome==0])) %>%
       gather(Variable, Count) %>%
       mutate(Revenue =
               case_when(Variable == "True_Negative"  ~ Count * 0,  
                         Variable == "True_Positive"  ~ ((Count * -2850) - ((Count * .25) * -5000)),  
                         Variable == "False_Negative" ~ Count * 0,
                         Variable == "False_Positive" ~ (Count * -2850))) %>%
    bind_cols(data.frame(Description = c(
              "Predicted correctly homeowner would not take the credit, no marketing resources were allocated, and no
              credit was allocated.",
              "Predicted correctly homeowner would take the credit; allocated the marketing resources, and 25% took
              the credit.", #25% take the 5000
              "We predicted that a homeowner would not take the credit but they did.",
              "Predicted incorrectly homeowner would take the credit; allocated marketing resources; no credit
              allocated.")))

kable(cost_benefit_table,
       caption = "Figure 8: Cost/Benefit Table") %>% kable_styling()
```

```{r , echo=FALSE}
iterateThresholds <- function(data) {
  x = .01
  all_prediction <- data.frame()
  while (x <= 1) {
  
  this_prediction <-
      testProbs %>%
      mutate(predOutcome = ifelse(Probs > x, 1, 0)) %>%
      count(predOutcome, Outcome) %>%
      summarize(True_Negative = sum(n[predOutcome==0 & Outcome==0]),
                True_Positive = sum(n[predOutcome==1 & Outcome==1]),
                False_Negative = sum(n[predOutcome==0 & Outcome==1]),
                False_Positive = sum(n[predOutcome==1 & Outcome==0])) %>%
     gather(Variable, Count) %>%
     mutate(Revenue =
               ifelse(Variable == "True_Negative", (Count * 0),
               ifelse(Variable == "True_Positive", ((Count * -2850) - ((Count * .25) * -5000)),
               ifelse(Variable == "False_Negative", (Count * 0),
               ifelse(Variable == "False_Positive", (Count * -2850), 0
                      )
               )
               )
               ),
            Threshold = x)
  
  all_prediction <- rbind(all_prediction, this_prediction)
  x <- x + .01
  }
return(all_prediction)
}
```

```{r , echo=FALSE}
whichThreshold <- iterateThresholds(testProbs)

whichThreshold_revenue <- 
whichThreshold %>% 
    group_by(Threshold) %>% 
    summarize(Revenue = sum(Revenue))

whichThreshold %>%
  ggplot(.,aes(Threshold, Revenue, colour = Variable)) +
  geom_point() +
  scale_colour_manual(values = palette5[c(5, 1:3)]) +    
  labs(title = "Figure 9: Revenue by confusion matrix type and threshold",
       y = "Revenue") +
  plotTheme() +
  guides(colour=guide_legend(title = "Confusion Matrix")) 
```

```{r , echo=FALSE}
whichThreshold_revenue <- 
  whichThreshold %>% 
    mutate(TookCredit = ifelse(Variable == "True_Positive", (Count * .25),
                         ifelse(Variable == "False_Negative", Count, 0))) %>%
  group_by(Threshold) %>% 
    summarize(Total_Revenue = sum(Revenue),
              Total_Count_Of_Credits = sum(TookCredit))

# Revenue 
grid.arrange(ncol = 1,
ggplot(whichThreshold_revenue)+ 
  geom_line(aes(x = Threshold, y = Total_Revenue))+
  geom_vline(xintercept =  pull(arrange(whichThreshold_revenue, -Total_Revenue)[1,1]))+
    labs(title = "Figure 10: Total Revenues By Threshold",
         subtitle = "Vertical Line Denotes Optimal Threshold"),
# Credits
ggplot(whichThreshold_revenue)+ 
  geom_line(aes(x = Threshold, y = Total_Count_Of_Credits))+
  geom_vline(xintercept =  pull(arrange(whichThreshold_revenue, -Total_Count_Of_Credits)[1,1]))+
    labs(title = "Figure 11: Total Count of Credits By Threshold",
         subtitle = "Vertical Line Denotes Optimal Threshold"))
```

```{r , echo=FALSE}
optimalthreshold <-
  whichThreshold_revenue %>%
  dplyr::select(Threshold, Total_Revenue, Total_Count_Of_Credits)

optimalthreshold_table <-
  whichThreshold_revenue %>%
  dplyr::select(Threshold, Total_Revenue, Total_Count_Of_Credits)

optimalthreshold_table <-
  optimalthreshold %>%
  filter(row(optimalthreshold) == c(25, 50))

kable(optimalthreshold_table,
       caption = "Cost/Benefit Table") %>% kable_styling()
```