---
title: "Midterm"
author: "Me"
date: "10/8/2021"
output: html_document
---
#Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(kableExtra)
library(jtools)     # for regression model plots
library(ggstance) 
```

## R Markdown

```{r cars}
#How is the zestimate calculated? https://www.zillow.com/z/zestimate/
muni <- 
  st_read("~/GitHub/MUSA-508/Municipalities.geojson") %>%
  st_transform('ESRI:102653')

studentData <- 
  st_read("~/GitHub/MUSA-508/studentData.geojson", crs = 'ESRI:102254') %>%
  st_transform('ESRI:102653')

  boulder.sf <- studentData %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102653')

  
ggplot() +
  geom_sf(data = nhoods, fill = "grey40") +
  geom_sf(data = boulder.sf, aes(colour = q5(price)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(boulder,"Price"),
                   name="Quintile\nBreaks") +
  labs(title="Price, Boulder") +
  mapTheme()

```
## Grab OSM Data 
```{r pressure, echo=FALSE}

library(osmdata)
library(tigris)

# Grab OSM data for Boulder County
# Check out the wiki for the key/value pairs for different amenities - that lets you #figure out what you can call from OSM #https://wiki.openstreetmap.org/wiki/Category:Tag_descriptions_by_value

# set bounding box - the maximum x-y extent you are interested in
# Do some right-clicking in google maps to figure this out

q0 <- opq(bbox = c(-75.3,39.85,-74.9,40.15)) #bounding box for philly
q0 <- opq(bbox = c(-105.21,36.00,40.05,24.00)) #bounding box for boulder
q0 <- opq(bbox = c("Boulder County")) #bounding box for boulder

# Parks

park <- add_osm_feature(opq = q0, key = 'leisure', value = "park") %>%
  osmdata_sf(.)

park.sf <- st_geometry(park$osm_polygons) %>%
  st_transform(4326) %>%
  st_sf() %>%
  cbind(., park$osm_polygons$name) %>%
  rename(NAME = park.osm_polygons.name)

# Transportation - Subway

subway <- add_osm_feature(opq = q0, key = 'railway', value = "subway") %>%
  osmdata_sf(.)

subway.sf <- st_geometry(subway$osm_lines) %>%
  st_transform(4326) %>%
  st_sf() %>%
  cbind(., subway$osm_lines$name) %>%
  rename(NAME = subway.osm_lines.name) %>%
  filter(NAME %in% c("Market-Frankford Line", "Broad Street Line"))

# Amenities - Restaurant

# Check in the attributes of `restaurant` and see what the different
# variables and values are.

# These data seem really shaky by the way

restaurant <- add_osm_feature(opq = q0, key = 'amenity', value = "restaurant") %>%
  osmdata_sf(.)

restaurant.sf <- st_geometry(restaurant$osm_points) %>%
  st_transform(4326) %>%
  st_sf() %>%
  cbind(., restaurant$osm_points$amenity) %>%
  rename(NAME = restaurant.osm_points.amenity)

# Add the features for Boulder County
# You can use this to clip things if it's necessary

coCounties <- counties(state = 'CO', cb = FALSE)

boulder <- coCounties %>%
  filter(NAME == "Boulder") %>%
  st_as_sf() %>%
  st_transform(4326)

# Map it

ggplot()+
  geom_sf(data = boulder, color = "black")+
  scale_color_manual(values = c("orange", "blue"))+
  geom_sf(data = park.sf, fill = "light green", color = "transparent")+
  geom_sf(data = restaurant.sf, color = "red", size = 0.2, alpha = 0.2)


```

```{r pressure, echo=FALSE}
#Grab open space data set
openspace <- 
  st_read("~/GitHub/MUSA-508/County_Open_Space.geojson") %>%
  filter(!is.na(PARK_GROUP)) %>%
  st_transform('ESRI:102653')

#Grab road data set
roads <-
  st_read("https://opendata.arcgis.com/datasets/f8292cbf379e4df7b9b8f62e21120ea7_0.geojson")%%
  st_transform('ESRI:102653') %>%
  filter(SPECIFIC_CATEGORY %in% c("State", "Municipal Primary"))

#Grab transit data set
```
